# adavantages of array over list

# time

In [43]:
import time

In [44]:
py_list=[i for i in range(1000000)]

In [45]:
#time  required for list
start=time.time()
py_list=[i+2 for i in py_list]
stop=time.time()
req_time=stop-start
print(req_time)

0.06745696067810059


In [46]:
import numpy as np

In [47]:
#time required for array
arr=np.array([i for i in range(1000000)])
start=time.time()
arr=arr+2
stop=time.time()
print(stop-start)

0.0018236637115478516


# storage space

In [49]:
import sys

In [50]:
#storage required to store list
list=[i for i in range(100)]
len(list)
print("total size required to store list=",sys.getsizeof(list[0])*len(list))

total size required to store list= 2400


In [51]:
#storage required to store array
arr=np.array([i for i in range(100)])
print("total size required to store list=",arr.itemsize*len(arr))

total size required to store list= 800


# numpy operations

In [58]:
import numpy as np

In [59]:
arr1=np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr1.shape

(3, 3)

In [63]:
arr1.size

9

In [65]:
np.sum(arr1)

45

In [66]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [67]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [68]:
arr2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [69]:
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [72]:
np.subtract(arr2,arr1)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [74]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [75]:
np.divide(arr2,arr1)

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [77]:
np.remainder(arr2,arr1)

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [78]:
arr3=arr1

In [79]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr3=np.append(arr3,[[10,11,12]],axis=0)         #add elements to the rows
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
np.append(arr3,[[13],[14],[15],[16]],axis=1)

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

# how to create scalar in numpy

In [96]:
import numpy as np

In [97]:
arr4=np.array([8])
print(arr4)

[8]


In [98]:
sc_arr4=np.asscalar(arr4)

/tmp/ipykernel_2425/398735811.py:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  sc_arr4=np.asscalar(arr4)


In [99]:
sc_arr4

8

In [100]:
type(sc_arr4)

int

# how to create vectors using numpy

In [101]:
l1=[1,2,3]
l1

[1, 2, 3]

In [102]:
type(l1)

list

In [104]:
l1=np.array(l1)

In [105]:
l1

array([1, 2, 3])

In [106]:
l2=[[11],
   [12],
   [13]]

In [107]:
type(l2)

list

In [108]:
l2=np.array(l2)

In [109]:
l2

array([[11],
       [12],
       [13]])

# how to create and work with matrix

In [113]:
m1=np.matrix('1,2,3;4,5,6;7,8,9')
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [114]:
type(m1)

numpy.matrix

In [115]:
m1.shape

(3, 3)

In [116]:
m1.size

9

In [117]:
m2=np.matrix('11,12,13;14,15,16;,17,18,19')
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [118]:
np.add(m1,m2)

matrix([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [119]:
np.subtract(m2,m1)

matrix([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [120]:
np.dot(m1,m2)

matrix([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

In [121]:
np.multiply(m1,m2)

matrix([[ 11,  24,  39],
        [ 56,  75,  96],
        [119, 144, 171]])

# linear algebra

In [122]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
det=np.linalg.det(m1)
det

6.66133814775094e-16

In [125]:
rank=np.linalg.matrix_rank(m1)
rank

2

In [127]:
inverse=np.linalg.inv(m1)
inverse

matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [128]:
arr7=np.matrix('1,2;3,4')
arr7

matrix([[1, 2],
        [3, 4]])

In [130]:
det_arr7=np.linalg.det(arr7)
round(det_arr7)

-2

In [131]:
inv_arr7=np.linalg.inv(arr7)
inv_arr7

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

# to solve linear algebraic equations

In [132]:
#2x-y=-1 & 3x+2y=9

In [135]:
a=np.matrix('2,-1;3,2')
a

matrix([[ 2, -1],
        [ 3,  2]])

In [137]:
b=np.matrix('-1;9')
b

matrix([[-1],
        [ 9]])

In [138]:
ans=np.linalg.solve(a,b)
ans

matrix([[1.],
        [3.]])

# broadcasting of arrays