# Broadcasting of an array

In [2]:
import numpy as np

In [3]:
array1=np.array([1,2,3,4])

In [4]:
array2=np.array([5])

In [5]:
array3=array1*array2

In [6]:
array3

array([ 5, 10, 15, 20])

In [7]:
type(array3)

numpy.ndarray

# sorting of an array

In [8]:
arr4=np.array([4,5,6])

In [9]:
np.sort(arr4)

array([4, 5, 6])

In [10]:
arr5=np.array(['pratibha','divya','tejashri'])
np.sort(arr5)

array(['divya', 'pratibha', 'tejashri'], dtype='<U8')

In [13]:
arr6=np.array([[3,2,1],[4,2,6]])

In [14]:
arr6

array([[3, 2, 1],
       [4, 2, 6]])

In [15]:
np.sort(arr6)

array([[1, 2, 3],
       [2, 4, 6]])

In [18]:
np.sort(arr6)[::-1]

array([[2, 4, 6],
       [1, 2, 3]])

In [19]:
np.sort(arr4)[::-1]

array([6, 5, 4])

In [4]:
import numpy as np

In [8]:
arr7=np.array([[9,5,7],[4,8,2],[8,3,6]])
arr7.sort(axis=0)
arr7

array([[4, 3, 2],
       [8, 5, 6],
       [9, 8, 7]])

In [11]:
arr7.sort(axis=1)
arr7

array([[2, 3, 4],
       [5, 6, 8],
       [7, 8, 9]])

# DATA CREATION

In [14]:
pip show pandas

Name: pandas
Version: 1.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /home/pratibhaantre/anaconda3/envs/python1/lib/python3.9/site-packages
Requires: numpy, python-dateutil, pytz
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [15]:
import pandas as pd

In [16]:
url="https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv"

In [17]:
df=pd.read_csv(url)

In [18]:
df

Index\tSachin\tDravid\tIndia
0               0\t100\t78\t342
1                1\t11\t62\t191
2                 2\t8\t85\t252
3                3\t71\t24\t307
4               4\t104\t17\t229
5               5\t18\t104\t246
6                 6\t8\t76\t226
7                7\t86\t74\t288
8                8\t12\t60\t216
9                9\t25\t90\t304
10            10\t56\t06\t272\t
11              11\t88\t69\t302
12             12\t147\t65\t312
13          13\t121\t146\t370\t
14             15\t99\t110\t362